### ISSUE TITLE
Add Elixir Language Support

### ISSUE THREAD

**Issue by asummers** [GoogleCloudPlatform/fluent-plugin-detect-exceptions#16]
Hello,

We are using the [Stackdriver](https://cloud.google.com/error-reporting/reference/rest/v1beta1/projects.events/report#reportederrorevent) logging, and are unable to see stacktraces from Elixir, even in the Raw view. My understanding from the docs is that only Python, PHP, Go, Java, C#, JavaScript and Ruby are supported. 

Questions:
1) Is this the library that determines that parsing ability?
2) If something is added to `master` here, would it eventually make it into production for StackDriver log error parsing? Given the language/iconography on the Stackdriver pages, I imagine that would be a larger product decision for Google for any level of official support, though we can deal with unofficially supported channels. We can reach out to our account contact if that is a more appropriate forum for that request.
3) Is it sufficient to add parsing rules to the code located [here](https://github.com/GoogleCloudPlatform/fluent-plugin-detect-exceptions/blob/fb64b91c7946068c6c6b3ab61247817c3bef9e4e/lib/fluent/plugin/exception_detector.rb#L94) and the proper keys added to `ALL_RULES` to detect Elixir stack traces or is there more that needs to be done to facilitate language support (plus tests and CLA, of course)?

Thank you,
Andrew

**Comment by qingling128** [comment]
Hi Andrew,

1. Yes.
2. Once a pull request is merged to the `master` branch here, we need to release a new version of this gem, update the gem spec in Stackdriver Logging agent to use the newly released gem, ask users to upgrade to the new Stackdriver Logging agent. At that point it's considered `in production`. And yes, any feature request will be triaged by our product manager.
3. Yes, once the feature request is approved, the change needed is: addition to the parsing rules in that file and corresponding tests.

**Comment by tlvenn** [comment]
Is there any public roadmap on Stackdriver regarding language support ? I am also interested with Elixir support and right now I can't leverage Stackdriver for the lack of support for it. Would be great to better understand if supporting Elixir is on the radar or not.

Thanks in advance.

**Comment by igorpeshansky** [comment]
Note: all this plugin does is detect when multiple lines constitute a single exception in one of the supported languages and joins them into a single multi-line log entry. The logging backend has separate code that recognizes these multi-line entries as exception traces, and they have a set of supported languages. Adding Error Reporting support for Elixir would require changes in the backend as well. Please send feedback with this feature request off the error reporting [documentation page](https://cloud.google.com/error-reporting/docs/) or [Cloud Console page](https://console.cloud.google.com/errors). Our product managers will review it and make a decision.
Note that Stackdriver has many other components (e.g., [debugger](https://cloud.google.com/debugger/docs/), [trace](https://cloud.google.com/trace/docs/), [client libraries](https://cloud.google.com/logging/docs/setup/)) that would need to support your language of choice if you want full integration.

**Comment by tlvenn** [comment]
Thanks for the clarification @igorpeshansky

**Comment by jkohen** [comment]
It looks like the question has been answered, and this is now pending the feature being implemented in the Stackdriver Logging backend. When that work happens, we'll add necessary support to the agent.
