### ISSUE TITLE
Ruby log not being picked up

### ISSUE THREAD

**Issue by ncloudsbconnelly** [GoogleCloudPlatform/fluent-plugin-detect-exceptions#38]
This is a fantastic plugin, I really appreciate your hard work. I have a Ruby log that is not being picked up and I am not sure how to go about fixing. The log example is at https://gist.github.com/ncloudsbconnelly/662819808dba3b98b0fd505d2aedafe0 . 

Thank you!

**Comment by igorpeshansky** [comment]
@ncloudsbconnelly, the current rules expect Ruby traces to start with a line that has "Error" in it. Yours doesn't. We're happy to review pull requests that improve exception detection.

**Comment by jkohen** [comment]
I'm cleaning up old issues. We haven't heard back from you since @igorpeshansky gave an answer, so I'll close this.
