### ISSUE TITLE
Golang HTTP handler stack traces not collapsed

### ISSUE THREAD

**Issue by vatine** [GoogleCloudPlatform/fluent-plugin-detect-exceptions#50]
With (at least) Go 1.11, panics thrown (and recovered) by any HTTP handler are printed in a format that is subtly different from a normal Go backtrace. I have raised pull request #49 to remedy this issue.

**Comment by ingvarm-gr** [comment]
I believe this can now be closed (PR to fix the issue, PR #49 was merged in August 2019).

**Comment by igorpeshansky** [comment]
Thanks, closing.
