### ISSUE TITLE
Recommended way to enable in k8s?

### ISSUE THREAD

**Issue by martinsson** [GoogleCloudPlatform/fluent-plugin-detect-exceptions#76]
I'd like to install this plug-in in my k8s cluster. 

No the only option that I can find is to build and maintain my own container like others have done (#31 and #39). I can certainly do that but it comes as a surprise that this is the official way of doing it given that almost every EFK installation will want this plugin. So I just wanted to check that this is really with the recommended way to enable it.

**Comment by igorpeshansky** [comment]
This plugin is automatically enabled on GKE. It is designed for use with [Google Cloud Error Reporting](https://cloud.google.com/error-reporting), and will likely be less useful in other contexts. The [official image for the Google Cloud Logging agent](https://gcr.io/stackdriver-agents/stackdriver-logging-agent) already contains that plugin.
If you want to install it on top of the upstream fluentd, then yes, maintaining your own Docker image is probably the way to go. We neither control nor distribute the official fluentd Docker images.
