### ISSUE TITLE
deadlock; recursive locking errors

### ISSUE THREAD

**Issue by mclarke47** [GoogleCloudPlatform/fluent-plugin-detect-exceptions#9]
Hi!

I've been trying to use this plugin with logs from kubernetes but I just keep getting deadlock; recursive locking errors.

[stack trace](https://gist.github.com/mclarke47/c5e3a585f0be480aa5cbdf3d9bff0ab4)
Config:
```
<match kubernetes.**>
      type detect_exceptions
      message log
      tag parsed.${tag}
      languages java
      multiline_flush_interval 5s
    </match>
```

Can you see anything obvious I am doing wrong?

**Comment by thomasschickinger** [comment]
Please try using remove_tag_prefix to modify the tag of your log entries. If you match on this prefix, you can ensure that the detect_exceptions plugin is not called recursively.

I guess we should even make remote_tag_prefix mandatory to avoid this type of setup problem.

**Comment by mclarke47** [comment]
Thanks for the quick reply. I'll try this and comment or close.

**Comment by nsaud01** [comment]
What were the results of this? Did everything work out alright?

**Comment by mclarke47** [comment]
Yes, this resolved my issue
